name: Validate Flatpak Submission

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If manually triggered, fetch the PR branch using the PR number
      - name: Checkout PR branch (manual trigger only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout "$PR_NUMBER"

      - name: Validate manifest
        run: |
          docker run -v $(pwd):/mnt --rm ghcr.io/flathub/flatpak-builder-lint:latest manifest /mnt/com.jetbrains.WebStorm.yaml
