name: Validate Flatpak Submission

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If manually triggered, fetch the PR branch using the PR number
      - name: Checkout PR branch (manual trigger only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout "$PR_NUMBER"

      - name: Download justfile and seccomp profile
        shell: python
        run: |
          import urllib3, os
          http = urllib3.PoolManager()
          base_url = "https://raw.githubusercontent.com/flathub-infra/vorarbeiter/refs/heads/main/"
          files = {"justfile": ".flathub.justfile", "flatpak.seccomp.json": "flatpak.seccomp.json"}
          for f, t in files.items():
            url = base_url + f
            r = http.request('GET', url)
            open(t, 'wb').write(r.data) if r.status == 200 else exit(1)

      - name: Validate manifest
        run: |
          docker run --rm \
            --security-opt seccomp=flatpak.seccomp.json \
            -v "${GITHUB_WORKSPACE}:/work" \
            -w /work \
            -e GITHUB_ACTIONS \
            ghcr.io/flathub-infra/flatpak-builder-lint:unprivileged \
            just -f .flathub.justfile validate-manifest .
